#!/bin/bash

set -e

BOOT_SSH_KEY=/mnt/boot/authorized_keys
HOME_SSH_KEY=/home/root/.ssh/authorized_keys

if [ -f $BOOT_SSH_KEY ]; then
    cp $BOOT_SSH_KEY $HOME_SSH_KEY
    chmod 0600 $HOME_SSH_KEY
fi
