image: ghcr.io/home-assistant/{arch}-hassio-supervisor
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.13-alpine3.22-2025.11.1
  amd64: ghcr.io/home-assistant/amd64-base-python:3.13-alpine3.22-2025.11.1
cosign:
  base_identity: https://github.com/home-assistant/docker-base/.*
  identity: https://github.com/home-assistant/supervisor/.*
args:
  COSIGN_VERSION: 2.5.3
labels:
  io.hass.type: supervisor
  org.opencontainers.image.title: Home Assistant Supervisor
  org.opencontainers.image.description: Container-based system for managing Home Assistant Core installation
  org.opencontainers.image.source: https://github.com/home-assistant/supervisor
  org.opencontainers.image.authors: The Home Assistant Authors
  org.opencontainers.image.url: https://www.home-assistant.io/
  org.opencontainers.image.documentation: https://www.home-assistant.io/docs/
  org.opencontainers.image.licenses: Apache License 2.0
