image: ghcr.io/home-assistant/{arch}-hassio-supervisor
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.12-alpine3.18
  armhf: ghcr.io/home-assistant/armhf-base-python:3.12-alpine3.18
  armv7: ghcr.io/home-assistant/armv7-base-python:3.12-alpine3.18
  amd64: ghcr.io/home-assistant/amd64-base-python:3.12-alpine3.18
  i386: ghcr.io/home-assistant/i386-base-python:3.12-alpine3.18
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
cosign:
  base_identity: https://github.com/home-assistant/docker-base/.*
  identity: https://github.com/home-assistant/supervisor/.*
args:
  COSIGN_VERSION: 2.2.3
labels:
  io.hass.type: supervisor
  org.opencontainers.image.title: Home Assistant Supervisor
  org.opencontainers.image.description: Container-based system for managing Home Assistant Core installation
  org.opencontainers.image.source: https://github.com/home-assistant/supervisor
  org.opencontainers.image.authors: The Home Assistant Authors
  org.opencontainers.image.url: https://www.home-assistant.io/
  org.opencontainers.image.documentation: https://www.home-assistant.io/docs/
  org.opencontainers.image.licenses: Apache License 2.0
