blank_issues_enabled: false
contact_links:
  - name: Report a bug/issues with an unsupported Supervisor
    url: https://community.home-assistant.io
    about: The Community guide can help or was updated to solve your issue

  - name: Report a bug for the Supervisor panel
    url: https://github.com/home-assistant/frontend/issues
    about: The Supervisor panel is a part of the Home Assistant frontend

  - name: Report incorrect or missing information on our developer documentation
    url: https://github.com/home-assistant/developers.home-assistant.io/issues
    about: Our documentation has its own issue tracker. Please report issues with the website there.

  - name: Request a feature for the Supervisor
    url: https://community.home-assistant.io/c/feature-requests
    about: Request an new feature for the Supervisor.

  - name: I have a question or need support
    url: https://www.home-assistant.io/help
    about: We use GitHub for tracking bugs, check our website for resources on getting help.

  - name: I'm unsure where to go?
    url: https://www.home-assistant.io/join-chat
    about: If you are unsure where to go, then joining our chat is recommended; Just ask!
