"""Discovery static data."""

ATTR_API_KEY = "api_key"
ATTR_HOST = "host"
ATTR_PASSWORD = "password"
ATTR_PORT = "port"
ATTR_PROTOCOL = "protocol"
ATTR_REST_PORT = "rest_port"
ATTR_SERIAL = "serial"
ATTR_SSL = "ssl"
ATTR_URL = "url"
ATTR_USERNAME = "username"
ATTR_WEB_SERVICE_PORT = "web_service_port"
