"""Constants for boards."""

BOARD_NAME_GREEN = "Green"
BOARD_NAME_RASPBERRYPI4 = "RaspberryPi4"
BOARD_NAME_RASPBERRYPI5 = "RaspberryPi5"
BOARD_NAME_SUPERVISED = "Supervised"
BOARD_NAME_YELLOW = "Yellow"

BOARDS_WITH_RPI_FIRMWARE = frozenset(
    {BOARD_NAME_RASPBERRYPI4, BOARD_NAME_RASPBERRYPI5, BOARD_NAME_YELLOW}
)
