"""Constants for network manager DBUS interface."""

DBUS_NAME_CONNECTION_ACTIVE = "org.freedesktop.NetworkManager.Connection.Active"
DBUS_NAME_DEVICE = "org.freedesktop.NetworkManager.Device"
DBUS_NAME_DNS = "org.freedesktop.NetworkManager.DnsManager"
DBUS_NAME_IP4CONFIG = "org.freedesktop.NetworkManager.IP4Config"
DBUS_NAME_NM = "org.freedesktop.NetworkManager"
DBUS_NAME_SETTINGS_CONNECTION = "org.freedesktop.NetworkManager.Settings.Connection"

DBUS_OBJECT_DNS = "/org/freedesktop/NetworkManager/DnsManager"
DBUS_OBJECT_NM = "/org/freedesktop/NetworkManager"

ATTR_ADDRESS = "address"
ATTR_ADDRESS_DATA = "AddressData"
ATTR_CONFIGURATION = "Configuration"
ATTR_CONNECTION = "Connection"
ATTR_CONNECTIONS = "connections"
ATTR_DEFAULT = "Default"
ATTR_DEVICE_INTERFACE = "Interface"
ATTR_DEVICE_TYPE = "DeviceType"
ATTR_DEVICES = "Devices"
ATTR_DOMAINS = "domains"
ATTR_FILENAME = "filename"
ATTR_FLAGS = "flags"
ATTR_GATEWAY = "Gateway"
ATTR_ID = "Id"
ATTR_INTERFACE = "interface"
ATTR_IP4ADDRESS = "Ip4Address"
ATTR_IP4CONFIG = "Ip4Config"
ATTR_MODE = "Mode"
ATTR_NAMESERVERS = "nameservers"
ATTR_PREFIX = "prefix"
ATTR_PRIMARY_CONNECTION = "primary connection"
ATTR_PRIORITY = "priority"
ATTR_RCMANAGER = "RcManager"
ATTR_REAL = "Real"
ATTR_STATE = "State"
ATTR_TYPE = "Type"
ATTR_UNSAVED = "unsaved"
ATTR_UUID = "Uuid"
ATTR_VPN = "vpn"
