#!/bin/bash

set -e

# Don't run anything before this source as it sets PATH here
source /etc/profile

# load config
source /usr/sbin/resin-vars
source /etc/resin-supervisor/supervisor.conf

#
# MAIN
#
while read cmd
do
    IFS=" " read -r -a parse <<< $cmd

    if [ ${parse[0]} == "info" ]; then
        echo "{ \"level\": 15, \"os\": \"resinos\", \"version\": \"$RESINOS_HASSIO_VERSION\", \"hostname\": \"$CONFIG_HOSTNAME\" }"
        continue
    fi
    if [ ${parse[0]} == "reboot" ]; then
        systemctl reboot && echo "OK" || echo "ERROR"
        continue
    fi
    if [ ${parse[0]} == "shutdown" ]; then
        systemctl poweroff && echo "OK" || echo "ERROR"
        continue
    fi
    if [ ${parse[0]} == "host-update" ]; then
        if [ ! -z ${parse[1]} ]; then
            nohup resinhub --hostos-version ${parse[1]} > /dev/null 2>&1 &
        else
            nohup resinhub > /dev/null 2>&1 &
        fi
        echo "OK"
        continue
    fi
    if [ ${parse[0]} == "supervisor-update" ]; then
        if [ ! -z ${parse[1]} ]; then
            nohup update-resin-supervisor --supervisor-tag ${parse[1]} > /dev/null 2>&1 &
        else
            nohup update-resin-supervisor > /dev/null 2>&1 &
        fi
        echo "OK"
        continue
    fi

    echo "WRONG"
done
