#!/bin/bash

set -e

# Don't run anything before this source as it sets PATH here
source /etc/profile

# load config
source /usr/sbin/resin-vars
source /etc/resin-supervisor/supervisor.conf

#
# MAIN
#
while read cmd
do
    IFS=" " read -r -a parse <<< $cmd

    if [ ${parse[0]} == "info" ]; then
        echo "{ \"host\": \"resinos\", \"version\": \"$RESINOS_HASSIO_VERSION\" }"
        continue
    fi
    if [ ${parse[0]} == "reboot" ]; then
        systemctl reboot || true
        echo "OK"
        continue
    fi
    if [ ${parse[0]} == "shutdown" ]; then
        systemctl poweroff || true
        echo "OK"
        continue
    fi
    if [ ${parse[0]} == "host-update" ]; then
        if [ ! -z ${parse[1]} ]; then
            resinhub --hostos-version ${parse[1]} || true
        else
            resinhub || true
        fi
        echo "OK"
        continue
    fi
    if [ ${parse[0]} == "supervisor-update" ]; then
        if [ ! -z ${parse[1]} ]; then
            update-resin-supervisor --supervisor-tag ${parse[1]} || true
        else
            update-resin-supervisor || true
        fi
        echo "OK"
        continue
    fi

    echo "ERROR"
done
